import { NextResponse } from "next/server";
import { generateWithGemini } from "@/lib/gemini";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { type, variant, title, fields, description, keyPoints, pageCount, showHeader } = body;

    if (!type || !variant) {
      return NextResponse.json({ error: "Type et variant requis" }, { status: 400 });
    }

    const baseInstruction =
      "Vous êtes un expert en rédaction de documents administratifs professionnels en français. " +
      "Votre texte doit être formel, précis et bien structuré. " +
      "Ne retournez QUE le texte demandé, sans commentaires et sans balises markdown de code (```).";

    // -------------------------------------------------------
    // LETTRE
    // -------------------------------------------------------
    if (type === "letter") {
      const bodyInstruction =
        baseInstruction +
        " Rédigez le corps de la lettre SUIVI de la formule de politesse, séparés par la balise ---FORMULE---. " +
        "Ne commencez pas par la salutation. " +
        "Format attendu :\n[paragraphes du corps]\n---FORMULE---\n[formule de politesse adaptée au type de lettre et au destinataire]";

      const bodyPrompt =
        `Rédigez le contenu d'une lettre administrative de type "${variant}".\n\n` +
        `Destinataire : ${[fields?.recipientName, fields?.recipientRole, fields?.recipientOrganization].filter(Boolean).join(", ")}\n` +
        `Objet : ${title || ""}\n` +
        `Contexte / instructions : ${fields?.body || description || "Rédigez un contenu cohérent, formel et professionnel selon l'objet."}\n\n` +
        `RÈGLE : rédigez les paragraphes du corps, puis sur une ligne seule ---FORMULE---, puis la formule de politesse adaptée (ex: "Veuillez agréer, Monsieur le Directeur, l'expression de mes salutations distinguées.").`;

      const generated = await generateWithGemini(bodyPrompt, bodyInstruction);

      // Split body and closing formula
      const parts = generated.split(/---FORMULE---/i);
      const generatedBody = (parts[0] || "").trim();
      const generatedClosing = (parts[1] || "").trim() ||
        "Veuillez agréer, Madame, Monsieur, l'expression de mes salutations distinguées.";

      // Build sender block
      const senderLines = [
        fields?.senderName,
        fields?.senderAddress,
        fields?.senderPhone,
        fields?.senderEmail,
      ].filter(Boolean).join("\n");

      // Build recipient block
      const recipientLines = [
        fields?.recipientName,
        fields?.recipientRole,
        fields?.recipientOrganization,
        fields?.recipientAddress,
      ].filter(Boolean).join("\n");

      // Date: "Cap-Haïtien, le 13 juin 2026" format
      const dateStr = [
        fields?.place || "",
        fields?.date ? `le ${fields.date}` : "",
      ].filter(Boolean).join(", ");

      // Salutation based on recipient role
      const salutation = fields?.recipientRole
        ? `Monsieur le ${fields.recipientRole},`
        : "Madame, Monsieur,";

      // Closing formula — generated by AI
      const closingFormula = generatedClosing;

      // Build content in the format parseLetterContent expects
      const contentLines = [
        `[[header:${showHeader === false ? "false" : "true"}]]`,
        `[[place:${fields?.place || ""}]]`,
        `[[date:${dateStr}]]`,
        "",
        "Expéditeur:",
        senderLines,
        "",
        "Destinataire:",
        recipientLines,
        "",
        `Objet: ${title || ""}`,
        "",
        salutation,
        "",
        generatedBody.trim(),
        "",
        "Formule de politesse:",
        closingFormula,
        "",
        "Signature:",
        fields?.signatureName || "",
      ];

      const content = contentLines.join("\n");
      return NextResponse.json({ content });
    }

    // Helper to process AI response with Title and Content
    const processAiResponse = async (prompt: string, fallbackTitle: string) => {
      const responseText = await generateWithGemini(prompt, baseInstruction);
      let generatedTitle = fallbackTitle;
      let generatedContent = responseText;
      
      const titleMatch = responseText.match(/:::TITLE:::\s*([\s\S]*?)\s*:::CONTENT:::/i);
      if (titleMatch) {
        generatedTitle = titleMatch[1].trim();
        const contentSplit = responseText.split(/:::CONTENT:::/i);
        if (contentSplit.length > 1) {
          generatedContent = contentSplit[1].trim();
        }
      }
      return { title: generatedTitle, content: generatedContent };
    };

    // -------------------------------------------------------
    // COMPTE RENDU
    // -------------------------------------------------------
    if (type === "compterendu") {
      const kpList =
        keyPoints?.length
          ? keyPoints
              .map((kp: any, i: number) =>
                `${i + 1}. ${kp.title}${kp.description ? ` : ${kp.description}` : ""}`
              )
              .join("\n")
          : "Non spécifié";

      const prompt =
        `Rédigez un compte rendu professionnel de type "${variant}".\n\n` +
        `Titre fourni par l'utilisateur : ${title}\n` +
        `Contexte : ${description}\n` +
        `Nombre de pages : ${pageCount || 1} (Maximum 2 pages, idéalement 1 seule page)\n` +
        `Points à traiter :\n${kpList}\n\n` +
        `ATTENTION - STRUCTURE DE RÉPONSE EXIGÉE :\n` +
        `:::TITLE:::\n[Générez un titre amélioré, très professionnel et impactant basé sur la demande]\n` +
        `:::CONTENT:::\n[Générez le corps du document ici]\n\n` +
        `Structure OBLIGATOIRE pour le :::CONTENT::: (Markdown) :\n` +
        `**Participants :**\n- ...\n\n` +
        `## 1. [Section]\n[contenu concis et direct]\n\n` +
        `## 2. [Section]\n[contenu concis et direct]\n\n` +
        `...etc\n\n` +
        `Le ton doit être institutionnel, formel, simple, précis et très clair. Ne dites pas de choses inutiles, allez à l'essentiel.`;

      const result = await processAiResponse(prompt, title);
      return NextResponse.json(result);
    }

    // -------------------------------------------------------
    // RAPPORT
    // -------------------------------------------------------
    if (type === "report") {
      const kpList =
        keyPoints?.length
          ? keyPoints
              .map((kp: any, i: number) =>
                `${i + 1}. ${kp.title}${kp.description ? ` : ${kp.description}` : ""}`
              )
              .join("\n")
          : "Aucun point spécifique fourni";

      const prompt =
        `Rédigez un rapport professionnel complet de type "${variant}".\n\n` +
        `Titre fourni par l'utilisateur : ${title}\n` +
        `Description : ${description}\n` +
        `Grands points à traiter obligatoirement :\n${kpList}\n\n` +
        `Nombre de pages : ${pageCount || 5}\n\n` +
        `ATTENTION - STRUCTURE DE RÉPONSE EXIGÉE :\n` +
        `:::TITLE:::\n[Générez un titre amélioré, très professionnel et impactant basé sur la demande]\n` +
        `:::CONTENT:::\n[Générez le corps du document ici]\n\n` +
        `RÈGLE ABSOLUE POUR LA PAGINATION ET LA STRUCTURE DU :::CONTENT::: :\n` +
        `1. Vous devez IMPÉRATIVEMENT utiliser le délimiteur ---PAGE--- (seul sur une ligne) pour forcer les sauts de page selon la structure suivante.\n` +
        `2. N'insérez JAMAIS de lignes horizontales (comme "---", "***", ou "___") dans le corps de votre texte. Utilisez UNIQUEMENT "---PAGE---" pour séparer.\n\n` +
        `Structure OBLIGATOIRE (Markdown) :\n` +
        `## Sommaire\n1. Introduction\n2. ...\nN. Conclusion\n\n` +
        `---PAGE---\n\n` +
        `## 1. Introduction\n[contenu de l'introduction sur une page unique]\n\n` +
        `---PAGE---\n\n` +
        `## 2. [Section]\n[contenu détaillé - utilisez ---PAGE--- si le développement est très long pour passer à une autre page]\n\n` +
        `...etc\n\n` +
        `---PAGE---\n\n` +
        `## Conclusion\n[contenu de la conclusion sur une page unique]\n\n` +
        `---PAGE---\n\n` +
        `## Annexes\n[s'il y a lieu, annexes sur une page unique]\n\n` +
        `Rédigez un contenu dense, professionnel et pertinent. Développez chaque section en profondeur et respectez STRICTEMENT l'usage de ---PAGE--- pour séparer Sommaire, Introduction, Contenu, Conclusion et Annexes.`;

      const result = await processAiResponse(prompt, title);
      return NextResponse.json(result);
    }

    return NextResponse.json({ error: "Type de document non pris en charge" }, { status: 400 });

  } catch (error: any) {
    console.error("Generate API Error:", error);
    return NextResponse.json(
      { error: error.message || "Une erreur est survenue lors de la génération" },
      { status: 500 }
    );
  }
}
