import { NextResponse } from "next/server";
import { generateWithGemini } from "@/lib/gemini";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { type, variant, title, fields, description, keyPoints, pageCount, showHeader } = body;

    if (!type || !variant) {
      return NextResponse.json({ error: "Type et variant requis" }, { status: 400 });
    }

    const baseInstruction =
      "Vous rédigez un document officiel pour l'Institut Haïtien de " +
      "Statistique et d'Informatique (IHSI), Direction Nord. " +
      "Le ton doit être formel, institutionnel, sobre et précis, " +
      "conforme aux standards de l'administration publique haïtienne. " +
      "Ne retournez QUE le texte demandé, sans commentaires et sans balises markdown de code (```).";

    // -------------------------------------------------------
    // LETTRE
    // -------------------------------------------------------
    if (type === "letter") {
      const bodyInstruction =
        baseInstruction +
        " Rédigez le corps de la lettre SUIVI de la formule de politesse, séparés par la balise ---FORMULE---. " +
        "Ne commencez pas par la salutation. " +
        "Format attendu :\n[paragraphes du corps]\n---FORMULE---\n[formule de politesse adaptée au type de lettre et au destinataire]";

      const bodyPrompt =
        `Rédigez le contenu d'une lettre administrative de type "${variant}".\n\n` +
        `Destinataire : ${[fields?.recipientName, fields?.recipientRole, fields?.recipientOrganization].filter(Boolean).join(", ")}\n` +
        `Objet : ${title || ""}\n` +
        `Contexte / instructions : ${fields?.body || description || "Rédigez un contenu cohérent, formel et professionnel selon l'objet."}\n\n` +
        `RÈGLE : rédigez les paragraphes du corps, puis sur une ligne seule ---FORMULE---, puis la formule de politesse adaptée (ex: "Veuillez agréer, Monsieur le Directeur, l'expression de mes salutations distinguées.").`;

      const generated = await generateWithGemini(bodyPrompt, bodyInstruction);

      // Split body and closing formula
      const parts = generated.split(/---FORMULE---/i);
      const generatedBody = (parts[0] || "").trim();
      const generatedClosing = (parts[1] || "").trim() ||
        "Veuillez agréer, Madame, Monsieur, l'expression de mes salutations distinguées.";

      // Build sender block
      const senderLines = [
        fields?.senderName,
        fields?.senderAddress,
        fields?.senderPhone,
        fields?.senderEmail,
      ].filter(Boolean).join("\n");

      // Build recipient block
      const recipientLines = [
        fields?.recipientName,
        fields?.recipientRole,
        fields?.recipientOrganization,
        fields?.recipientAddress,
      ].filter(Boolean).join("\n");

      // Date: "Cap-Haïtien, le 13 juin 2026" format
      const dateStr = [
        fields?.place || "",
        fields?.date ? `le ${fields.date}` : "",
      ].filter(Boolean).join(", ");

      // Salutation based on recipient role
      const salutation = fields?.recipientRole
        ? `Monsieur le ${fields.recipientRole},`
        : "Madame, Monsieur,";

      // Closing formula — generated by AI
      const closingFormula = generatedClosing;

      // Build content in the format parseLetterContent expects
      const contentLines = [
        `[[header:${showHeader === false ? "false" : "true"}]]`,
        `[[place:${fields?.place || ""}]]`,
        `[[date:${dateStr}]]`,
        "",
        "Expéditeur:",
        senderLines,
        "",
        "Destinataire:",
        recipientLines,
        "",
        `Objet: ${title || ""}`,
        "",
        salutation,
        "",
        generatedBody.trim(),
        "",
        "Formule de politesse:",
        closingFormula,
        "",
        "Signature:",
        fields?.signatureName || "",
      ];

      const content = contentLines.join("\n");
      return NextResponse.json({ content });
    }

    // Helper to process AI response with Title and Content
    const processAiResponse = async (prompt: string, fallbackTitle: string) => {
      const responseText = await generateWithGemini(prompt, baseInstruction);
      let generatedTitle = fallbackTitle;
      let generatedContent = responseText;
      
      const titleMatch = responseText.match(/:::TITLE:::\s*([\s\S]*?)\s*:::CONTENT:::/i);
      if (titleMatch) {
        generatedTitle = titleMatch[1].trim();
        const contentSplit = responseText.split(/:::CONTENT:::/i);
        if (contentSplit.length > 1) {
          generatedContent = contentSplit[1].trim();
        }
      }
      return { title: generatedTitle, content: generatedContent };
    };

    // -------------------------------------------------------
    // COMPTE RENDU
    // -------------------------------------------------------
    if (type === "compterendu") {
      const kpList =
        keyPoints?.length
          ? keyPoints
              .map((kp: any, i: number) =>
                `${i + 1}. ${kp.title}${kp.description ? ` : ${kp.description}` : ""}`
              )
              .join("\n")
          : "Non spécifié";

      const prompt =
        `Vous rédigez un document officiel pour l'Institut Haïtien de ` +
        `Statistique et d'Informatique (IHSI), Direction Nord. ` +
        `Le ton doit être formel, institutionnel, sobre et précis, ` +
        `conforme aux standards de l'administration publique haïtienne.\n\n` +
        `Rédigez un compte rendu professionnel complet de type '${variant}'.\n\n` +
        `INFORMATIONS FOURNIES :\n` +
        `- Titre : ${title}\n` +
        `- Contexte : ${description}\n` +
        `- Points à traiter obligatoirement :\n${kpList}\n\n` +
        `CONTRAINTE IMPORTANTE : Le contenu doit tenir sur UNE SEULE PAGE (format 8.5 x 11). ` +
        `Soyez extrêmement concis, direct et précis.\n\n` +
        `STRUCTURE OBLIGATOIRE EN MARKDOWN (respectez EXACTEMENT cet ordre) :\n\n` +
        `:::TITLE:::\n[Titre officiel du document]\n` +
        `:::CONTENT:::\n\n` +
        `## Contexte et objectifs\n` +
        `[Maximum 25 mots. Expliquez brièvement le contexte et les objectifs.]\n\n` +
        `## Déroulement\n` +
        `[Maximum 30 mots par point. Pour chaque point, rédigez un paragraphe très concis.]\n\n` +
        `## Résultats et acquis\n` +
        `[Maximum 25 mots. Synthèse très rapide des décisions.]\n\n` +
        `## Recommandations et perspectives\n` +
        `[Maximum 20 mots. Actions principales à entreprendre.]\n\n` +
        `## Conclusion\n` +
        `[Maximum 15 mots. Clôture formelle.]\n\n` +
        `INTERDICTIONS ABSOLUES :\n` +
        `- N'utilisez jamais d'expressions familières ou informelles.\n` +
        `- Ne répétez jamais les informations déjà données.\n` +
        `- N'inventez aucun chiffre, statistique ou nom de personne.\n` +
        `- N'ajoutez aucune balise markdown de code.\n` +
        `- Ne mettez pas de texte entre crochets comme [contenu ici].\n` +
        `- Ne laissez aucune section vide ou avec du texte de remplacement.\n` +
        `- N'ajoutez PAS de tableau de participants.\n` +
        `- N'utilisez PAS le délimiteur ---PAGE---.\n` +
        `- N'utilisez JAMAIS de lignes horizontales (---, ***, ___, ou tout autre tiret).\n` +
        `- N'utilisez JAMAIS de bordures sous les titres.\n` +
        `- Respectez strictement les limites de mots pour tenir sur une seule page.`;

      const result = await processAiResponse(prompt, title);
      return NextResponse.json(result);
    }

    // -------------------------------------------------------
    // RAPPORT
    // -------------------------------------------------------
    if (type === "report") {
      const kpList =
        keyPoints?.length
          ? keyPoints
              .map((kp: any, i: number) =>
                `${i + 1}. ${kp.title}${kp.description ? ` : ${kp.description}` : ""}`
              )
              .join("\n")
          : "Aucun point spécifique fourni";

      const prompt =
        `Vous rédigez un document officiel pour l'Institut Haïtien de ` +
        `Statistique et d'Informatique (IHSI), Direction Nord.\n` +
        `Le ton doit être formel, analytique et précis, conforme aux ` +
        `standards de l'administration publique haïtienne.\n\n` +
        `Rédigez un rapport professionnel complet de type '${variant}'.\n\n` +
        `INFORMATIONS FOURNIES :\n` +
        `- Titre : ${title}\n` +
        `- Description : ${description}\n` +
        `- Nombre de pages cible : ${pageCount || 5}\n` +
        `- Points à traiter obligatoirement :\n${kpList}\n\n` +
        `RÈGLE DE PAGINATION :\n` +
        `Utilisez UNIQUEMENT ---PAGE--- (seul sur une ligne) pour séparer ` +
        `les pages. N'utilisez JAMAIS --- seul comme séparateur ou décoration.\n\n` +
        `STRUCTURE OBLIGATOIRE EN MARKDOWN :\n\n` +
        `:::TITLE:::\n[Titre officiel du rapport]\n` +
        `:::CONTENT:::\n\n` +
        `## Sommaire\n` +
        `1. Introduction\n` +
        `2. [Sections selon les points fournis]\n` +
        `N. Conclusion\n` +
        `[Éventuellement : Annexes]\n\n` +
        `---PAGE---\n\n` +
        `## 1. Introduction\n` +
        `[Minimum 120 mots. Contexte général, raison d'être du rapport, ` +
        `portée et limites, méthodologie utilisée. Rédigez en prose, ` +
        `à la 3e personne institutionnelle.]\n\n` +
        `---PAGE---\n\n` +
        `## 2. [Titre de la section selon les points fournis]\n` +
        `[Minimum 150 mots par section. Développez chaque point en profondeur ` +
        `avec des sous-sections si nécessaire. Utilisez ### pour les ` +
        `sous-sections. Insérez ---PAGE--- si la section est très longue.]\n\n` +
        `[Répétez ce bloc pour chaque point de la liste fourni]\n\n` +
        `---PAGE---\n\n` +
        `## Conclusion\n` +
        `[Minimum 100 mots. Synthèse des points traités, appréciation ` +
        `générale, impact attendu, recommandations finales formulées ` +
        `de manière institutionnelle.]\n\n` +
        `---PAGE---\n\n` +
        `## Annexes\n` +
        `[Si pertinent : tableaux de données, références, textes de loi ` +
        `cités, glossaire. Sinon, omettez cette section entièrement.]\n\n` +
        `INTERDICTIONS ABSOLUES :\n` +
        `- N'utilisez jamais d'expressions familières ou informelles.\n` +
        `- Ne répétez jamais les informations déjà données.\n` +
        `- N'inventez aucun chiffre, statistique ou nom de personne.\n` +
        `- N'ajoutez aucune balise markdown de code.\n` +
        `- Ne laissez aucune section vide ou avec du texte de remplacement.\n` +
        `- N'utilisez PAS --- seul comme décoration ou séparateur visuel.\n` +
        `- Utilisez UNIQUEMENT ---PAGE--- pour les sauts de page.`;

      const result = await processAiResponse(prompt, title);
      return NextResponse.json(result);
    }

    return NextResponse.json({ error: "Type de document non pris en charge" }, { status: 400 });

  } catch (error: any) {
    console.error("Generate API Error:", error);
    return NextResponse.json(
      { error: error.message || "Une erreur est survenue lors de la génération" },
      { status: 500 }
    );
  }
}
